<?php

return [
    'C' => 'Ciudad Aut&oacute;noma de Buenos Aires',
    'B' => 'Buenos Aires',
    'K' => 'Catamarca',
    'H' => 'Chaco',
    'U' => 'Chubut',
    'X' => 'C&oacute;rdoba',
    'W' => 'Corrientes',
    'E' => 'Entre R&iacute;os',
    'P' => 'Formosa',
    'Y' => 'Jujuy',
    'L' => 'La Pampa',
    'F' => 'La Rioja',
    'M' => 'Mendoza',
    'N' => 'Misiones',
    'Q' => 'Neuqu&eacute;n',
    'R' => 'R&iacute;o Negro',
    'A' => 'Salta',
    'J' => 'San Juan',
    'D' => 'San Luis',
    'Z' => 'Santa Cruz',
    'S' => 'Santa Fe',
    'G' => 'Santiago del Estero',
    'V' => 'Tierra del Fuego',
    'T' => 'Tucum&aacute;n',
];
