<?php

return [
    'AC' => 'Acre',
    'AL' => 'Alagoas',
    'AP' => 'Amap&aacute;',
    'AM' => 'Amazonas',
    'BA' => 'Bahia',
    'CE' => 'Cear&aacute;',
    'DF' => 'Distrito Federal',
    'ES' => 'Esp&iacute;rito Santo',
    'GO' => 'Goi&aacute;s',
    'MA' => 'Maranh&atilde;o',
    'MT' => 'Mato Grosso',
    'MS' => 'Mato Grosso do Sul',
    'MG' => 'Minas Gerais',
    'PA' => 'Par&aacute;',
    'PB' => 'Para&iacute;ba',
    'PR' => 'Paran&aacute;',
    'PE' => 'Pernambuco',
    'PI' => 'Piau&iacute;',
    'RJ' => 'Rio de Janeiro',
    'RN' => 'Rio Grande do Norte',
    'RS' => 'Rio Grande do Sul',
    'RO' => 'Rond&ocirc;nia',
    'RR' => 'Roraima',
    'SC' => 'Santa Catarina',
    'SP' => 'S&atilde;o Paulo',
    'SE' => 'Sergipe',
    'TO' => 'Tocantins',
];
