<?php

return [
    'AG' => 'Aargau',
    'AR' => 'Appenzell Ausserrhoden',
    'AI' => 'Appenzell Innerrhoden',
    'BL' => 'Basel-Landschaft',
    'BS' => 'Basel-Stadt',
    'BE' => 'Bern',
    'FR' => 'Fribourg',
    'GE' => 'Geneva',
    'GL' => 'Glarus',
    'GR' => 'Graub&uuml;nden',
    'JU' => 'Jura',
    'LU' => 'Luzern',
    'NE' => 'Neuch&acirc;tel',
    'NW' => 'Nidwalden',
    'OW' => 'Obwalden',
    'SH' => 'Schaffhausen',
    'SZ' => 'Schwyz',
    'SO' => 'Solothurn',
    'SG' => 'St. Gallen',
    'TG' => 'Thurgau',
    'TI' => 'Ticino',
    'UR' => 'Uri',
    'VS' => 'Valais',
    'VD' => 'Vaud',
    'ZG' => 'Zug',
    'ZH' => 'Z&uuml;rich',
];
