<?php

return [
    'CN1' => 'Yunnan',
    'CN2' => 'Beijing',
    'CN3' => 'Tianjin',
    'CN4' => 'Hebei',
    'CN5' => 'Shanxi',
    'CN6' => 'Inner Mongolia',
    'CN7' => 'Liaoning',
    'CN8' => 'Jilin',
    'CN9' => 'Heilongjiang',
    'CN10' => 'Shanghai',
    'CN11' => 'Jiangsu',
    'CN12' => 'Zhejiang',
    'CN13' => 'Anhui',
    'CN14' => 'Fujian',
    'CN15' => 'Jiangxi',
    'CN16' => 'Shandong',
    'CN17' => 'Henan',
    'CN18' => 'Hubei',
    'CN19' => 'Hunan',
    'CN20' => 'Guangdong',
    'CN21' => 'Guangxi Zhuang',
    'CN22' => 'Hainan',
    'CN23' => 'Chongqing',
    'CN24' => 'Sichuan',
    'CN25' => 'Guizhou',
    'CN26' => 'Shaanxi',
    'CN27' => 'Gansu',
    'CN28' => 'Qinghai',
    'CN29' => 'Ningxia Hui',
    'CN30' => 'Macau',
    'CN31' => 'Tibet',
    'CN32' => 'Xinjiang',
];
