<?php

return [
    'AC' => 'Daerah Istimewa Aceh',
    'SU' => 'Sumatera Utara',
    'SB' => 'Sumatera Barat',
    'RI' => 'Riau',
    'KR' => 'Kepulauan Riau',
    'JA' => 'Jambi',
    'SS' => 'Sumatera Selatan',
    'BB' => 'Bangka Belitung',
    'BE' => 'Bengkulu',
    'LA' => 'Lampung',
    'JK' => 'DKI Jakarta',
    'JB' => 'Jawa Barat',
    'BT' => 'Banten',
    'JT' => 'Jawa Tengah',
    'JI' => 'Jawa Timur',
    'YO' => 'Daerah Istimewa Yogyakarta',
    'BA' => 'Bali',
    'NB' => 'Nusa Tenggara Barat',
    'NT' => 'Nusa Tenggara Timur',
    'KB' => 'Kalimantan Barat',
    'KT' => 'Kalimantan Tengah',
    'KI' => 'Kalimantan Timur',
    'KS' => 'Kalimantan Selatan',
    'KU' => 'Kalimantan Utara',
    'SA' => 'Sulawesi Utara',
    'ST' => 'Sulawesi Tengah',
    'SG' => 'Sulawesi Tenggara',
    'SR' => 'Sulawesi Barat',
    'SN' => 'Sulawesi Selatan',
    'GO' => 'Gorontalo',
    'MA' => 'Maluku',
    'MU' => 'Maluku Utara',
    'PA' => 'Papua',
    'PB' => 'Papua Barat',
];
