<?php

return [
    'CW' => 'Carlow',
    'CN' => 'Cavan',
    'CE' => 'Clare',
    'CK' => 'Cork',
    'DL' => 'Donegal',
    'DN' => 'Dublin',
    'GY' => 'Galway',
    'KY' => 'Kerry',
    'KE' => 'Kildare',
    'KK' => 'Kilkenny',
    'LS' => 'Laois',
    'LM' => 'Leitrim',
    'LK' => 'Limerick',
    'LD' => 'Longford',
    'LH' => 'Louth',
    'MO' => 'Mayo',
    'MH' => 'Meath',
    'MN' => 'Monaghan',
    'OY' => 'Offaly',
    'RN' => 'Roscommon',
    'SO' => 'Sligo',
    'TY' => 'Tipperary',
    'WD' => 'Waterford',
    'WH' => 'Westmeath',
    'WX' => 'Wexford',
    'WW' => 'Wicklow',
];
