<?php

return [
    'KHZ' => 'Khuzestan',
    'THR' => 'Tehran',
    'ILM' => 'Ilaam',
    'BHR' => 'Bushehr',
    'ADL' => 'Ardabil',
    'ESF' => 'Isfahan',
    'YZD' => 'Yazd',
    'KRH' => 'Kermanshah',
    'KRN' => 'Kerman',
    'HDN' => 'Hamadan',
    'GZN' => 'Ghazvin',
    'ZJN' => 'Zanjan',
    'LRS' => 'Luristan',
    'ABZ' => 'Alborz',
    'EAZ' => 'East Azarbaijan',
    'WAZ' => 'West Azarbaijan',
    'CHB' => 'Chaharmahal and Bakhtiari',
    'SKH' => 'South Khorasan',
    'RKH' => 'Razavi Khorasan',
    'NKH' => 'North Khorasan',
    'SMN' => 'Semnan',
    'FRS' => 'Fars',
    'QHM' => 'Qom',
    'KRD' => 'Kurdistan',
    'KBD' => 'Kohgiluyeh and BoyerAhmad',
    'GLS' => 'Golestan',
    'GIL' => 'Gilan',
    'MZN' => 'Mazandaran',
    'MKZ' => 'Markazi',
    'HRZ' => 'Hormozgan',
    'SBN' => 'Sistan and Baluchestan',
];
