<?php

return [
    'C' => 'Chi&#537;in&#259;u',
    'BL' => 'B&#259;l&#539;i',
    'AN' => 'Anenii Noi',
    'BS' => 'Basarabeasca',
    'BR' => 'Briceni',
    'CH' => 'Cahul',
    'CT' => 'Cantemir',
    'CL' => 'C&#259;l&#259;ra&#537;i',
    'CS' => 'C&#259;u&#537;eni',
    'CM' => 'Cimi&#537;lia',
    'CR' => 'Criuleni',
    'DN' => 'Dondu&#537;eni',
    'DR' => 'Drochia',
    'DB' => 'Dub&#259;sari',
    'ED' => 'Edine&#539;',
    'FL' => 'F&#259;le&#537;ti',
    'FR' => 'Flore&#537;ti',
    'GE' => 'UTA G&#259;g&#259;uzia',
    'GL' => 'Glodeni',
    'HN' => 'H&icirc;nce&#537;ti',
    'IL' => 'Ialoveni',
    'LV' => 'Leova',
    'NS' => 'Nisporeni',
    'OC' => 'Ocni&#539;a',
    'OR' => 'Orhei',
    'RZ' => 'Rezina',
    'RS' => 'R&icirc;&#537;cani',
    'SG' => 'S&icirc;ngerei',
    'SR' => 'Soroca',
    'ST' => 'Str&#259;&#537;eni',
    'SD' => '&#536;old&#259;ne&#537;ti',
    'SV' => '&#536;tefan Vod&#259;',
    'TR' => 'Taraclia',
    'TL' => 'Telene&#537;ti',
    'UN' => 'Ungheni',
];
