<?php

return [
    'DF' => 'Ciudad de M&eacute;xico',
    'JA' => 'Jalisco',
    'NL' => 'Nuevo Le&oacute;n',
    'AG' => 'Aguascalientes',
    'BC' => 'Baja California',
    'BS' => 'Baja California Sur',
    'CM' => 'Campeche',
    'CS' => 'Chiapas',
    'CH' => 'Chihuahua',
    'CO' => 'Coahuila',
    'CL' => 'Colima',
    'DG' => 'Durango',
    'GT' => 'Guanajuato',
    'GR' => 'Guerrero',
    'HG' => 'Hidalgo',
    'MX' => 'Estado de M&eacute;xico',
    'MI' => 'Michoac&aacute;n',
    'MO' => 'Morelos',
    'NA' => 'Nayarit',
    'OA' => 'Oaxaca',
    'PU' => 'Puebla',
    'QT' => 'Quer&eacute;taro',
    'QR' => 'Quintana Roo',
    'SL' => 'San Luis Potos&iacute;',
    'SI' => 'Sinaloa',
    'SO' => 'Sonora',
    'TB' => 'Tabasco',
    'TM' => 'Tamaulipas',
    'TL' => 'Tlaxcala',
    'VE' => 'Veracruz',
    'YU' => 'Yucat&aacute;n',
    'ZA' => 'Zacatecas',
];
