<?php

return [
    'CAL' => 'El Callao',
    'LMA' => 'Municipalidad Metropolitana de Lima',
    'AMA' => 'Amazonas',
    'ANC' => 'Ancash',
    'APU' => 'Apur&iacute;mac',
    'ARE' => 'Arequipa',
    'AYA' => 'Ayacucho',
    'CAJ' => 'Cajamarca',
    'CUS' => 'Cusco',
    'HUV' => 'Huancavelica',
    'HUC' => 'Hu&aacute;nuco',
    'ICA' => 'Ica',
    'JUN' => 'Jun&iacute;n',
    'LAL' => 'La Libertad',
    'LAM' => 'Lambayeque',
    'LIM' => 'Lima',
    'LOR' => 'Loreto',
    'MDD' => 'Madre de Dios',
    'MOQ' => 'Moquegua',
    'PAS' => 'Pasco',
    'PIU' => 'Piura',
    'PUN' => 'Puno',
    'SAM' => 'San Mart&iacute;n',
    'TAC' => 'Tacna',
    'TUM' => 'Tumbes',
    'UCA' => 'Ucayali',
];
