<?php

return [
    'AB' => 'Alba',
    'AR' => 'Arad',
    'AG' => 'Arge&#537;',
    'BC' => 'Bac&#259;u',
    'BH' => 'Bihor',
    'BN' => 'Bistri&#539;a-N&#259;s&#259;ud',
    'BT' => 'Boto&#537;ani',
    'BR' => 'Br&#259;ila',
    'BV' => 'Bra&#537;ov',
    'B' => 'Bucure&#537;ti',
    'BZ' => 'Buz&#259;u',
    'CL' => 'C&#259;l&#259;ra&#537;i',
    'CS' => 'Cara&#537;-Severin',
    'CJ' => 'Cluj',
    'CT' => 'Constan&#539;a',
    'CV' => 'Covasna',
    'DB' => 'D&acirc;mbovi&#539;a',
    'DJ' => 'Dolj',
    'GL' => 'Gala&#539;i',
    'GR' => 'Giurgiu',
    'GJ' => 'Gorj',
    'HR' => 'Harghita',
    'HD' => 'Hunedoara',
    'IL' => 'Ialomi&#539;a',
    'IS' => 'Ia&#537;i',
    'IF' => 'Ilfov',
    'MM' => 'Maramure&#537;',
    'MH' => 'Mehedin&#539;i',
    'MS' => 'Mure&#537;',
    'NT' => 'Neam&#539;',
    'OT' => 'Olt',
    'PH' => 'Prahova',
    'SJ' => 'S&#259;laj',
    'SM' => 'Satu Mare',
    'SB' => 'Sibiu',
    'SV' => 'Suceava',
    'TR' => 'Teleorman',
    'TM' => 'Timi&#537;',
    'TL' => 'Tulcea',
    'VL' => 'V&acirc;lcea',
    'VS' => 'Vaslui',
    'VN' => 'Vrancea',
];
