<?php

return [
    'TZ01' => 'Arusha',
    'TZ02' => 'Dar es Salaam',
    'TZ03' => 'Dodoma',
    'TZ04' => 'Iringa',
    'TZ05' => 'Kagera',
    'TZ06' => 'Pemba North',
    'TZ07' => 'Zanzibar North',
    'TZ08' => 'Kigoma',
    'TZ09' => 'Kilimanjaro',
    'TZ10' => 'Pemba South',
    'TZ11' => 'Zanzibar South',
    'TZ12' => 'Lindi',
    'TZ13' => 'Mara',
    'TZ14' => 'Mbeya',
    'TZ15' => 'Zanzibar West',
    'TZ16' => 'Morogoro',
    'TZ17' => 'Mtwara',
    'TZ18' => 'Mwanza',
    'TZ19' => 'Coast',
    'TZ20' => 'Rukwa',
    'TZ21' => 'Ruvuma',
    'TZ22' => 'Shinyanga',
    'TZ23' => 'Singida',
    'TZ24' => 'Tabora',
    'TZ25' => 'Tanga',
    'TZ26' => 'Manyara',
    'TZ27' => 'Geita',
    'TZ28' => 'Katavi',
    'TZ29' => 'Njombe',
    'TZ30' => 'Simiyu',
];
